--<ScriptOptions statementTerminator=";"/>

CREATE TABLE MONSTERS (
		ID INTEGER NOT NULL,
		Level INTEGER NOT NULL,
		Name TEXT(2000000000) NOT NULL,
		Type TEXT(2000000000) NOT NULL,
		HP INTEGER NOT NULL,
		Strength INTEGER NOT NULL,
		Constitution INTEGER NOT NULL,
		Wisdom INTEGER NOT NULL,
		Intelligence INTEGER NOT NULL,
		Dexterity INTEGER NOT NULL,
		Charisma INTEGER NOT NULL,
		AC INTEGER NOT NULL,
		Reflex INTEGER NOT NULL,
		Fortitude INTEGER NOT NULL,
		Will INTEGER NOT NULL,
		Abilities TEXT(2000000000) NOT NULL
	);

